import { getGraphData } from "@/features/graph/actions";
import { GraphView } from "@/components/graph/graph-view";
import { BrainCircuit } from "lucide-react";

export default async function GraphPage() {
  const { nodes, edges } = await getGraphData();

  return (
    <div className="space-y-6 animate-in fade-in duration-700">
      
      {/* Header */}
      <div>
        <div className="flex items-center gap-3 mb-2">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-neutral-900 text-white dark:bg-white dark:text-black">
            <BrainCircuit size={20} />
          </div>
          <h1 className="text-3xl font-light tracking-tight text-neutral-900 dark:text-white">
            Knowledge Graph
          </h1>
        </div>
        <p className="text-neutral-500 max-w-xl">
          Visualizing the neural pathways of your second brain. 
          Connections are automatically generated by AI based on content similarity.
        </p>
      </div>

      {/* The Graph */}
      {nodes.length > 0 ? (
        <GraphView initialNodes={nodes} initialEdges={edges} />
      ) : (
        <div className="py-20 text-center border rounded-xl border-dashed border-neutral-300 dark:border-neutral-700">
          <p className="text-neutral-500">Not enough data to generate a graph yet.</p>
          <p className="text-sm text-neutral-400">Create more notes with AI content to see connections.</p>
        </div>
      )}
    </div>
  );
}